language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
    - $HOME/.cache/webpack/node_modules
install: "pip install git+https://github.com/lektor/lektor.git#egg=lektor"
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy ghpages"
