language: python
python: 2.7
install: "pip install git+https://github.com/singingwolfboy/lektor.git@fix-ghpages-https-deploy#egg=lektor"
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy ghpages"
